[package]
name = "pcp"
version = "0.2.0"
edition = "2021"

[dependencies]
blake3 = "1.8.2"
clap = { version = "4.5.20", features = ["derive"] }
dirs = "5.0.1"
filetime = "0.2.25"
indicatif = "0.17.9"
num_cpus = "1.16.0"
os_str_bytes = "7.1.1"
rayon = "1.10.0"
walkdir = "2.5.0"
